### ISSUE TITLE
Encoding 

### ISSUE THREAD

**Issue by RarexWU16** [RarexWU16/wubot#9]
Vi måste fixa så att åäö och andra utf8 tecken fungerar.

**Comment by JNodbrant** [comment]
Är riktigt konstigt för alla filer verkar vara i utf-8. Kolla längst ner på den blåa raden is vsCode om det står utf-8 där för dig också

**Comment by RarexWU16** [comment]
Jag kör VisualStudio! Men det ska vara UTF-8 hela vägen.. förstår inte varför det inte funkar att skicka det till slack.

**Comment by RarexWU16** [comment]
Helt plöstligt fungerar UTF-8 som det ska
